#!/usr/bin/python3
#!/usr/bin/python

import urwid
from subprocess import call, Popen, PIPE

def menu(title, choices):
    body = [urwid.Text(title), urwid.Divider()]
    for c in sorted(choices.keys()):
        button = urwid.Button(choices[c])
        urwid.connect_signal(button, 'click', item_chosen, c)
        body.append(urwid.AttrMap(button, None, focus_map='reversed'))
    return urwid.ListBox(urwid.SimpleFocusListWalker(body))

def item_chosen(button, choice):
    call(['wemux', 'j', choice])
    call(['wemux', 'rogue'])
    raise urwid.ExitMainLoop()


servers = {}
for line in Popen(['wemux', 'l'], stdout=PIPE).stdout.readlines()[1::]:
    server_name = line.decode().split()[1]
    
    users = []
    for client_description in Popen(['tmux', '-S', '/tmp/wemux-'+str(server_name), 'list-clients'], stdout=PIPE).stdout.readlines():
        users.append(client_description.split()[1].decode().split('-')[1])

    servers[server_name] = server_name.ljust(10) + (' [' + ','.join(users) + '] ').ljust(20) + ' http://bit.ly/bokeh-' + server_name




main = urwid.Padding(menu('Who says penguins can\'t fly?', servers), left=2, right=2)
top = urwid.Overlay(main, urwid.SolidFill(u'\N{MEDIUM SHADE}'),
    align='center', width=('relative', 60),
    valign='middle', height=('relative', 60),
    min_width=20, min_height=9)
urwid.MainLoop(top, palette=[('reversed', 'standout', '')]).run()
