#!/bin/bash

ARGUMENT_LIST=(
    "filter:"
    "exclude-group:"
    "testdox"
    "testdox-text:"
)


# read arguments
opts=$(getopt \
    --longoptions "$(printf "%s," "${ARGUMENT_LIST[@]}")" \
    --name "$(basename "$0")" \
    --options "c:" \
    -- "$@"
    )

eval set --$opts

while [[ $# -gt 0 ]]; do
    case "$1" in
        --filter)
            filter="--filter $2"
            shift 2
            ;;

	--testdox)
	    testdox="--testdox"
	    shift
	    ;;

	--testdox-text)
	    testdox="--testdox-text $2"
	    shift 2
	    ;;

	--exclude-group)
	    excludeGroup="--exclude-group $2"
	    shift 2
	    ;;
	
        -c)
	    configFile=${2/opt\/workplace/home\/webmaster}
            configOption="-c $configFile"
            shift 2
            ;;

        *)
            className=$2
	    fileName=$3
	    #shift 2
	    break
            ;;
    esac
done

me=$(whoami)
fileName=${fileName/opt\/workplace/home\/webmaster}
pwd=$(pwd)
place_to_be=${pwd/opt\/workplace/home\/webmaster}
container=$(docker ps|grep "$me-bokeh-php"|awk '{print $1}')

command="docker exec -w $place_to_be --env XDEBUG_CONFIG=\"${XDEBUG_CONFIG}\" $container su webmaster -c \"phpunit $configOption $filter $testdox $excludeGroup $className $fileName\""

echo -e "\n$(fortune fr)\n\n${command}\n\n"
eval $command | sed  "s/home\/webmaster/opt\/workplace/g"

