---
- hosts: bokehlocaux
  user: webmaster
  tasks:
    - name: test connection
      shell: cat upgrade-opac.sh


- hosts: moulins
  user: root
  tasks:
    - name: test connection
      shell: /root/upgrade-opac.sh


